# fly.toml app configuration file generated for beadpantry-api on 2025-09-03T16:25:26-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'beadpantry-api'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  release_command = 'bundle exec rails db:migrate'

[env]
  PORT = '8080'
  RAILS_LOG_TO_STDOUT = '1'
  RAILS_SERVE_STATIC_FILES = 'true'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 30
    soft_limit = 20

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
